services:
  api:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env